name: "Test-falilure"
on:
  pull_request:
    branches: ["main"]
permissions:
  pull-requests: write
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out repo"
        uses: actions/checkout@v4

      - name: "Installing dependencies"
        run: "npm install"

      - name: "Linting"
        id: lint
        run: "npm run lint"

      # - name: "Checking if error"
      #   if: steps.lint.outcome != 'success'
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/${{github.repository}}/issues/${{github.event.pull_request.number}}/comments \
      #     -d '{"body":"Hey, ${{github.actor}}!\nLooks like the code check failed. Could you run pnpm format:fix and push again?"}'
  printing:
    runs-on: ubuntu-latest
    needs: ['testing']
    if: always() && contains(needs.testing.result, 'failure')
    steps:
      - name: "Checking if error"
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/issues/${{github.event.pull_request.number}}/comments \
          -d '{"body":"Hey, ${{github.actor}}!\nLooks like the code check failed. Could you run pnpm format:fix and push again?"}'
